[package]
name = "lidar"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
rand = "0.8.5"
serde = "1.0.215"
bevy_common_assets = { version = "0.11.0", features = ["ron"] }
bevy_mod_raycast = "0.18.0"
